# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Nouvelles
    url: post
    weight: 10
  - name: Évènements
    url: event
    weight: 20
  - name: Comité
    url: people
    weight: 30
  - name: À propos
    url: about 
    weight: 60
